"""empty message

Revision ID: 059ac6bb84e1
Revises: 8f587187dd61
Create Date: 2016-09-20 11:52:17.411286

"""

# revision identifiers, used by Alembic.
revision = '059ac6bb84e1'
down_revision = '8f587187dd61'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nfcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=64), nullable=False),
    sa.Column('rolling_key', sa.String(length=64), nullable=False),
    sa.Column('old_rolling_key', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nfcs')
    ### end Alembic commands ###
