"""empty message

Revision ID: dc6311d1a2ef
Revises: 8fb858c24120
Create Date: 2016-09-08 19:25:06.473956

"""

# revision identifiers, used by Alembic.
revision = 'dc6311d1a2ef'
down_revision = '8fb858c24120'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('api_key', sa.String(length=64), nullable=False),
    sa.Column('device_owners', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('allowed_users', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('returned_attributes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devices')
    ### end Alembic commands ###
